#!/bin/bash
# step-25-update-web-files.sh - Update web files after deployment
# Run this script after step-20-deploy.sh when you've made changes to web files

set -e # Exit on any error

# Welcome banner
echo "=================================================="
echo "   CloudFront Cognito Serverless Application     "
echo "              Web Files Update Script            "
echo "=================================================="
echo

# Check if .env exists
if [ ! -f .env ]; then
    echo "❌ .env file not found. Please run step-20-deploy.sh first."
    exit 1
fi

# Load environment variables
source .env

# Validate required variables
if [ -z "$APP_NAME" ] || [ -z "$STAGE" ] || [ -z "$S3_BUCKET_NAME" ]; then
    echo "❌ Missing required variables in .env file. Please run step-20-deploy.sh first."
    exit 1
fi

# Check for AWS CLI configuration
if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS CLI is not configured properly. Please run 'aws configure' first."
    exit 1
fi

# Update the app.js from template
echo "📝 Creating app.js from template..."
if [ -f web/app.js.template ]; then
    cp web/app.js.template web/app.js
    echo "✅ app.js created from template"
else
    echo "❌ ERROR: app.js.template not found!"
    exit 1
fi

echo "📝 Updating app.js with deployment values..."
if [ -f web/app.js ]; then
    sed -i.bak "s|YOUR_USER_POOL_ID|$USER_POOL_ID|g" web/app.js
    sed -i.bak "s|YOUR_USER_POOL_CLIENT_ID|$USER_POOL_CLIENT_ID|g" web/app.js
    sed -i.bak "s|YOUR_IDENTITY_POOL_ID|$IDENTITY_POOL_ID|g" web/app.js
    sed -i.bak "s|YOUR_CLOUDFRONT_API_ENDPOINT|$CLOUDFRONT_API_ENDPOINT|g" web/app.js
    sed -i.bak "s|YOUR_CLOUDFRONT_S3_API_ENDPOINT|${CLOUDFRONT_URL}/api/s3/list|g" web/app.js
    sed -i.bak "s|YOUR_API_ENDPOINT|$CLOUDFRONT_API_ENDPOINT|g" web/app.js
    sed -i.bak "s|YOUR_APP_URL|$CLOUDFRONT_URL|g" web/app.js
    sed -i.bak "s|YOUR_COGNITO_DOMAIN_PREFIX|$COGNITO_DOMAIN|g" web/app.js

    # Add large warning to the top of app.js
    WARNING="// WARNING: THIS FILE IS AUTO-GENERATED BY THE DEPLOYMENT SCRIPT.\n// DO NOT EDIT DIRECTLY AS YOUR CHANGES WILL BE OVERWRITTEN.\n// EDIT app.js.template INSTEAD.\n"
    sed -i.bak "1s|^|$WARNING\n|" web/app.js
    
    echo "✅ app.js updated with deployment values"
else
    echo "❌ ERROR: app.js file could not be created or found!"
    exit 1
fi

# Upload the website files to S3
echo "📤 Uploading website files to S3..."
aws s3 cp web/ s3://$S3_BUCKET_NAME/ --recursive

# Create a CloudFront invalidation
echo "🔄 Creating CloudFront invalidation..."
DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?DomainName=='$(echo $CLOUDFRONT_URL | sed 's|https://||')'].Id" --output text)
if [ -n "$DISTRIBUTION_ID" ]; then
    aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
    echo "✅ Created CloudFront invalidation for all paths"
else
    echo "⚠️ Warning: Could not determine CloudFront distribution ID"
fi

echo
echo "✅ Web files update completed successfully!"
echo
echo "🔗 Your application: $CLOUDFRONT_URL"
echo
echo "⚠️ Note: It may take a few minutes for the CloudFront invalidation to complete."
echo "⚠️ Changes should be visible in 1-2 minutes."
echo "=================================================="